<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">
	
<xacro:include filename="$(find aros_description)/urdf/common.xacro" />
	   
<xacro:macro name="aros_fingers_v0" params="prefix parent">
	
<!-- finger 1 -->
    <link name="${prefix}_finger1_base_link">
	 <visual>
        <geometry>
              <mesh filename="package://aros_description/meshes/hand/finger/base/body.dae" />
        </geometry>
      </visual>		

	<collision>
	  <geometry>
		<mesh filename="package://aros_description/meshes/hand/finger/base/link.dae" />
	  </geometry>
	</collision>
	</link>	
	
  <joint name="${prefix}_finger1_joint_base" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="${EFFORT}" lower="${finger_base_lower}" upper="${finger_base_upper}" velocity="${VELOCITY}"/>
    <parent link="${prefix}_${parent}_link"/>
    <child link="${prefix}_finger1_base_link"/>
    <origin xyz="${finger_base_x} ${finger_base_y} ${finger_base_z}" rpy="${finger_base_roll} ${finger_base_pitch} ${finger_base_yaw}"/>
  </joint>
	
	<link name="${prefix}_finger1_1_link">
	 <visual>
        <geometry>
              <mesh filename="package://aros_description/meshes/hand/finger/link1/body.dae" />
        </geometry>
      </visual>		

	<collision>
	  <geometry>
		<mesh filename="package://aros_description/meshes/hand/finger/link1/link.dae" />
	  </geometry>
	</collision>
	</link>
	
  <joint name="${prefix}_finger1_joint1" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="${EFFORT}" lower="${finger_1_lower}" upper="${finger_1_upper}" velocity="${VELOCITY}"/>
    <parent link="${prefix}_finger1_base_link"/>
    <child link="${prefix}_finger1_1_link"/>
    <origin xyz="${finger_1_x} ${finger_1_y} ${finger_1_z}" rpy="${finger_1_roll} ${finger_1_pitch} ${finger_1_yaw}"/>
  </joint>
	
	<link name="${prefix}_finger1_2_link">
	 <visual>
        <geometry>
              <mesh filename="package://aros_description/meshes/hand/finger/link2/body.dae" />
        </geometry>
      </visual>		

	<collision>
	  <geometry>
		<mesh filename="package://aros_description/meshes/hand/finger/link2/link.dae" />
	  </geometry>
	</collision>
	</link>
	
  <joint name="${prefix}_finger1_joint2" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="${EFFORT}" lower="${finger_2_lower}" upper="${finger_2_upper}" velocity="${VELOCITY}"/>
    <parent link="${prefix}_finger1_1_link"/>
    <child link="${prefix}_finger1_2_link"/>
    <origin xyz="${finger_2_x} ${finger_2_y} ${finger_2_z}" rpy="${finger_2_roll} ${finger_2_pitch} ${finger_2_yaw}"/>
  </joint>	

<!--	
	<link name="${prefix}_finger1_tip_link">
	 <visual>
        <geometry>
              <mesh filename="package://aros_description/meshes/hand/finger/tip/body.dae" />
        </geometry>
      </visual>		
	</link>
	
  <joint name="${prefix}_finger1_joint_tip" type="fixed">
    <parent link="${prefix}_finger1_2_link"/>
    <child link="${prefix}_finger1_tip_link"/>
    <origin xyz="${finger_tip_x} ${finger_tip_y} ${finger_tip_z}" rpy="${finger_tip_roll} ${finger_tip_pitch} ${finger_tip_yaw}"/>
  </joint>
-->

	
<!-- finger 2 -->
    <link name="${prefix}_finger2_base_link">
	 <visual>
        <geometry>
              <mesh filename="package://aros_description/meshes/hand/finger/base/body.dae" />
        </geometry>
      </visual>		

	<collision>
	  <geometry>
		<mesh filename="package://aros_description/meshes/hand/finger/base/link.dae" />
	  </geometry>
	</collision>
	</link>	
	
  <joint name="${prefix}_finger2_joint_base" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="${EFFORT}" lower="${-finger_base_upper}" upper="${-finger_base_lower}" velocity="${VELOCITY}"/>
    <parent link="${prefix}_${parent}_link"/>
    <child link="${prefix}_finger2_base_link"/>
    <origin xyz="${-finger_base_x} ${finger_base_y} ${finger_base_z}" rpy="${finger_base_roll} ${finger_base_pitch} ${finger_base_yaw}"/>
  </joint>
	
	<link name="${prefix}_finger2_1_link">
	 <visual>
        <geometry>
              <mesh filename="package://aros_description/meshes/hand/finger/link1/body.dae" />
        </geometry>
      </visual>		

	<collision>
	  <geometry>
		<mesh filename="package://aros_description/meshes/hand/finger/link1/link.dae" />
	  </geometry>
	</collision>
	</link>
	
  <joint name="${prefix}_finger2_joint1" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="${EFFORT}" lower="${finger_1_lower}" upper="${finger_1_upper}" velocity="${VELOCITY}"/>
    <parent link="${prefix}_finger2_base_link"/>
    <child link="${prefix}_finger2_1_link"/>
    <origin xyz="${finger_1_x} ${finger_1_y} ${finger_1_z}" rpy="${finger_1_roll} ${finger_1_pitch} ${finger_1_yaw}"/>
  </joint>
	
	<link name="${prefix}_finger2_2_link">
	 <visual>
        <geometry>
              <mesh filename="package://aros_description/meshes/hand/finger/link2/body.dae" />
        </geometry>
      </visual>		

	<collision>
	  <geometry>
		<mesh filename="package://aros_description/meshes/hand/finger/link2/link.dae" />
	  </geometry>
	</collision>
	</link>
	
  <joint name="${prefix}_finger2_joint2" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="${EFFORT}" lower="${finger_2_lower}" upper="${finger_2_upper}" velocity="${VELOCITY}"/>
    <parent link="${prefix}_finger2_1_link"/>
    <child link="${prefix}_finger2_2_link"/>
    <origin xyz="${finger_2_x} ${finger_2_y} ${finger_2_z}" rpy="${finger_2_roll} ${finger_2_pitch} ${finger_2_yaw}"/>
  </joint>	
	
<!--
	<link name="${prefix}_finger2_tip_link">
	 <visual>
        <geometry>
              <mesh filename="package://aros_description/meshes/hand/finger/tip/body.dae" />
        </geometry>
      </visual>		
	</link>
	
  <joint name="${prefix}_finger2_joint_tip" type="fixed">
    <parent link="${prefix}_finger2_2_link"/>
    <child link="${prefix}_finger2_tip_link"/>
    <origin xyz="${finger_tip_x} ${finger_tip_y} ${finger_tip_z}" rpy="${finger_tip_roll} ${finger_tip_pitch} ${finger_tip_yaw}"/>
  </joint>
-->
<!-- finger 3 -->
	
	<link name="${prefix}_finger3_1_link">
	 <visual>
        <geometry>
              <mesh filename="package://aros_description/meshes/hand/finger/link1/body.dae" />
        </geometry>
      </visual>		

	<collision>
	  <geometry>
		<mesh filename="package://aros_description/meshes/hand/finger/link1/link.dae" />
	  </geometry>
	</collision>
	</link>
	
  <joint name="${prefix}_finger3_joint1" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="${EFFORT}" lower="${finger_1_lower}" upper="${finger_1_upper}" velocity="${VELOCITY}"/>
    <parent link="${prefix}_${parent}_link"/>
    <child link="${prefix}_finger3_1_link"/>
    <origin xyz="${finger_1_y} ${finger_1_x} ${finger_1_z-0.028}" rpy="${finger_1_roll-M_PI/2} ${finger_1_pitch} ${finger_1_yaw}"/>
  </joint>
	
	<link name="${prefix}_finger3_2_link">
	 <visual>
        <geometry>
              <mesh filename="package://aros_description/meshes/hand/finger/link2/body.dae" />
        </geometry>
      </visual>		

	<collision>
	  <geometry>
		<mesh filename="package://aros_description/meshes/hand/finger/link2/link.dae" />
	  </geometry>
	</collision>
	</link>
	
  <joint name="${prefix}_finger3_joint2" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="${EFFORT}" lower="${finger_2_lower}" upper="${finger_2_upper}" velocity="${VELOCITY}"/>
    <parent link="${prefix}_finger3_1_link"/>
    <child link="${prefix}_finger3_2_link"/>
    <origin xyz="${finger_2_x} ${finger_2_y} ${finger_2_z}" rpy="${finger_2_roll} ${finger_2_pitch} ${finger_2_yaw}"/>
  </joint>	

<!--	
	<link name="${prefix}_finger3_tip_link">
	 <visual>
        <geometry>
              <mesh filename="package://aros_description/meshes/hand/finger/tip/body.dae" />
        </geometry>
      </visual>		
	</link>
	
  <joint name="${prefix}_finger3_joint_tip" type="fixed">
    <parent link="${prefix}_finger3_2_link"/>
    <child link="${prefix}_finger3_tip_link"/>
    <origin xyz="${finger_tip_x} ${finger_tip_y} ${finger_tip_z}" rpy="${finger_tip_roll} ${finger_tip_pitch} ${finger_tip_yaw}"/>
  </joint>
-->
	
</xacro:macro>
	
</robot>